### ISSUE TITLE
Would you please check new version for 4.Beta

### ISSUE THREAD

**Issue by mhnmoa** [mmdsharifi/Bootstrap4-RTL#3]
Would you please check new version for 4.Beta

**Comment by mmdsharifi** [comment]
Hi @mhnmoa ,
Thanks for your feedback, I update repository ASAP. If have time PRs are welcome :grinning:

**Comment by mmdsharifi** [comment]
:tada:  see updated  demo!

**Comment by mhnmoa** [comment]
Thanks!
